// app/layout.tsx
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Healthcare System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Wait for Clerk to load before rendering children */}
          <ClerkLoaded>{children}</ClerkLoaded>

          {/* Show spinner while Clerk initializes */}
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen">
              <p className="text-gray-500 text-lg">Loading...</p>
            </div>
          </ClerkLoading>

          <Toaster richColors position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
